name: stats

on:
  push: 
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
      permissons:
        
    steps:
      - name: setup-python
      - uses: actions/setup-python@v5
        with: 
          python-versión: '3.12'
      - run: python ./FastAPI/main.py

      - name: commit and push
      - uses: stefanzweifel/git-auto-commit-action@v5
        - commit_user_name: Sergio Toral [GitHub Actions]
